# Generated by Django 5.0.6 on 2024-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_members_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
